### ISSUE TITLE
Linux Build

### ISSUE THREAD

**Issue by SimplyCorbett** [SuperiorServers/gmsv_fps#2]
Could we get a Linux build of this?

**Comment by aStonePenguin** [comment]
I have no way to compile this on linux, someone else will need to.

**Comment by thelastpenguin** [comment]
I can probably get a Linux compile going at somepoint maybe. Learning to
cross compile is on my todo list. I'm working from a Mac running Linux in
parallels right now.

**Comment by aStonePenguin** [comment]
#3
